baseURL: https://blog.toposcope.co/
languageCode: fr-fr
title: "Le Blog Toposcope"

theme: "PaperMod"

menu:
    main:
        - name: Toposcope.co
          url: https://toposcope.co
          weight: 5

params:
    author: Hugo (et son GPT)
    ShowReadingTime: true
    DateFormat: "2/1/2006"
