languageCode: fr
defaultContentLanguage: fr
baseURL: https://blog.toposcope.co/

title: "Le Blog Toposcope"

theme: "PaperMod"

googleAnalytics: "G-FEMQLX2ERG"

menu:
    main:
        - name: Toposcope.co
          url: https://toposcope.co
          weight: 5

params:
    author: Hugo
    ShowReadingTime: true
    DateFormat: "2 January 2006" # "2/1/2006"

    env: production